
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: braintrust-bot-rails-dev

test:
  <<: *default
  database: braintrust-bot-rails-test


# In production, the database configuration is decided via the `DATABASE_URL`
# environment variable. If nothing is specified here, it will take precedence.

#production:
#  <<: *default
#  database: db/production.sqlite3
