# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4c552521c3989e16bef5acb5bb1ad5e46eeb04a0d16e23c5cc3688d20c86b0bf1688604a0ee0017ebd0d7a2a770c7539e1317a31c2992c90295ae8bec00be5da
  telegram:
    bot:
      token: <%= ENV['BOT_TOKEN'] %>
      username: <%= ENV['BOT_NAME'] %>

test:
  secret_key_base: 3090ff0f692db35ff2571335be6aa8f6fc7ed820dcb1eab7e899089f9000f7d4c415aa4fe64f800b94bbc4880e24a3a0c7c6c07fef7d7629bf7e8c1054d2eea3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
